import type { UnitTypeId } from './definitions';
import { getUnitType } from './definitions';

export type Orientation = 'x' | 'z';

export interface Cell {
  x: number;
  z: number;
}

export interface UnitCell extends Cell {
  layer: number;
}

export interface UnitInstance {
  /** Stable id for this placement (ulid-like, generated by caller). */
  id: string;
  typeId: UnitTypeId;
  /** Anchor cell (x,z) of the unit; layer comes from the type. */
  anchor: Cell;
  orientation: Orientation;
  cells: UnitCell[];
  hits: Set<string>;
  sunk: boolean;
}

export function createUnit(
  id: string,
  typeId: UnitTypeId,
  anchor: Cell,
  orientation: Orientation,
): UnitInstance {
  const type = getUnitType(typeId);
  const cells = computeCells(type.layer, type.length, anchor, orientation);
  return {
    id,
    typeId,
    anchor,
    orientation,
    cells,
    hits: new Set<string>(),
    sunk: false,
  };
}

export function computeCells(
  layer: number,
  length: number,
  anchor: Cell,
  orientation: Orientation,
): UnitCell[] {
  const cells: UnitCell[] = [];
  for (let i = 0; i < length; i++) {
    if (orientation === 'x') {
      cells.push({ x: anchor.x + i, z: anchor.z, layer });
    } else {
      cells.push({ x: anchor.x, z: anchor.z + i, layer });
    }
  }
  return cells;
}

export function cellKey(layer: number, x: number, z: number): string {
  return `${layer}:${x}:${z}`;
}

export function unitContainsCell(unit: UnitInstance, layer: number, x: number, z: number): boolean {
  if (unit.cells.length === 0) return false;
  if (unit.cells[0]!.layer !== layer) return false;
  return unit.cells.some((c) => c.x === x && c.z === z);
}
